<?php

/**
 * This file errors example
 *
 * @api example
 * @author example
 * @category example
 * @copyright example
 * @example example
 * @filesource example
 * @global example
 * @ignore example
 * @internal example
 * @license example
 * @link example
 * @method example
 * @package example
 * @since example
 * @source example
 * @subpackage example
 * @uses example example example
 *                 exaple examle
 * @used-by example
 * @version example
 * @param float $a
 * @return bool
 */

$a = rand(0, 1);
